apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: fluent-bit
        command:
        - /bin/sh
        args:
        - -c
        - |
          export S3_BUCKET_NAME="${S3_BUCKET#s3://}"; \
          exec /entrypoint.sh -R /fluent-bit/etc/lake-parsers.conf -c /fluent-bit/etc/fluent-bit.conf
        volumeMounts:
        - name: fluent-bit-pipeline-lake-inputs
          mountPath: /fluent-bit/etc/pipeline-lake-inputs.conf
          subPath: pipeline-lake-inputs.conf
        - name: fluent-bit-pipeline-lake-filters
          mountPath: /fluent-bit/etc/pipeline-lake-filters.conf
          subPath: pipeline-lake-filters.conf
        - name: fluent-bit-pipeline-lake-parsers
          mountPath: /fluent-bit/etc/lake-parsers.conf
          subPath: lake-parsers.conf
        - name: fluent-bit-pipeline-lake-outputs
          mountPath: /fluent-bit/etc/pipeline-lake-outputs.conf
          subPath: pipeline-lake-outputs.conf
      volumes:
      - name: fluent-bit-pipeline-lake-inputs
        configMap:
          name: fluent-bit-pipeline-lake-inputs
      - name: fluent-bit-pipeline-lake-filters
        configMap:
          name: fluent-bit-pipeline-lake-filters
      - name: fluent-bit-pipeline-lake-parsers
        configMap:
          name: fluent-bit-pipeline-lake-parsers
      - name: fluent-bit-pipeline-lake-outputs
        configMap:
          name: fluent-bit-pipeline-lake-outputs
