apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: elastic-stack-logging
spec:
  template:
    spec:
      containers:
      - name: fluent-bit
        volumeMounts:
        - name: fluent-bit-pipeline-lake
          mountPath: /fluent-bit/etc/pipeline-lake.conf
          subPath: pipeline-lake.conf
      volumes:
      - name: fluent-bit-pipeline-lake
        configMap:
          name: fluent-bit-pipeline-lake
