apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit-lake-patch.yaml

configMapGenerator:
- name: fluent-bit-pipeline-lake-inputs
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-lake-inputs.conf
- name: fluent-bit-pipeline-lake-filters
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-lake-filters.conf
- name: fluent-bit-pipeline-lake-parsers
  namespace: elastic-stack-logging
  files:
  - configs/lake-parsers.conf
- name: fluent-bit-pipeline-lake-outputs
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-lake-outputs.conf
