apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit-lake-patch.yaml

configMapGenerator:
- name: fluent-bit-pipeline-lake
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-lake.conf
