apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit-hipaa-patch.yaml

configMapGenerator:
- name: fluent-bit-pipeline-hipaa
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-hipaa.conf
