apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: fluentbit-hipaa-patch.yaml

configMapGenerator:
- name: fluent-bit-pipeline-hipaa-inputs
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-hipaa-inputs.conf
- name: fluent-bit-pipeline-hipaa-filters
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-hipaa-filters.conf
- name: fluent-bit-pipeline-hipaa-outputs
  namespace: elastic-stack-logging
  files:
  - configs/pipeline-hipaa-outputs.conf
