input {
  http {
    port => 8086
    codec => json
  }
}

filter {
  # Drop healthcheck probes
  if ([headers][request_method] == "GET") {
    drop {}
  }

  mutate {
    add_field => { "[@metadata][s3_key]" => "hipaa" }
  }
}

output {
  s3 {
    region => "${AWS_REGION}"
    bucket => "${HIPAA_BUCKET_NAME}"
    prefix => "/application/%{[@metadata][s3_key]}/%{+YYYY}/%{+MM}/%{+dd}/%{+HH}/%{+mm}"
    time_file => "3"
    # Flush logs to S3 when file size reaches 100 MB (104857600 bytes)
    size_file => "104857600"
    codec => "json_lines"
    id => "hipaa_s3_out"
  }
}
