# =============================================================================
# pipeline-hipaa-outputs.conf
# HIPAA-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.hipaa.general.*
    Host                logstash-elastic-compliance
    Port                8086
    Format              json
    storage.total_limit_size  1G
    Retry_Limit         15
    workers             1
