# =============================================================================
# pipeline-hipaa-outputs.conf
# HIPAA-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Alias               hipaa_logstash_out
    Match               elk.hipaa.general.*
    workers             1
    Host                logstash-elastic-compliance.elastic-stack-logging
    Port                8086
    Format              json
    Retry_Limit         15
    compress            gzip
    net.keepalive_idle_timeout  10
    net.keepalive_max_recycle   30
    storage.total_limit_size    1G
