# =============================================================================
# pipeline-lake-outputs.conf
# Lake-specific Fluent Bit outputs
# =============================================================================

[OUTPUT]
    Name                http
    Match               elk.lake.general.*
    Host                logstash-elastic-compliance
    Port                8085
    Format              json
    storage.total_limit_size  1G
    Retry_Limit         15
    workers             1
