# =============================================================================
# pipeline-lake-inputs.conf
# Lake-specific Fluent Bit inputs
# =============================================================================

[INPUT]
    Name                tail
    Tag                 elk.lake.general.*
    Path                /var/log/containers/pingfederate-[0-9]*_ping-cloud_pingfederate-[0-9a-f]*.log
    multiline.parser    docker, cri
    DB                  /fluent-bit/state/flb_lake_ping.db
    Skip_Long_Lines     Off
    Refresh_Interval    20
    Rotate_Wait         10
    Buffer_Chunk_Size   2M
    Buffer_Max_Size     8M
    Mem_Buf_Limit       8M
    storage.type        filesystem
    storage.pause_on_chunks_overlimit on
    Read_from_Head      ${READ_FROM_HEAD}
